name: "inti_the_inka_chess_game"
version: 1.2.0+23
publish_to: none
description: "A mini board game"
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.3
  http: ^1.3.0
  connectivity_plus: ^6.1.3
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.1
  firebase_crashlytics: ^4.3.4
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  firebase_notifications_handler: ^2.0.2+1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  #google_sign_in: ^6.0.2
  #google_sign_in_web: ^0.11.0+2
  get: ^4.7.2
  flutter: 
    sdk: flutter
  shared_preferences: ^2.2.0
  file_picker: ^9.1.0
  crypto: ^3.0.3
  url_launcher: ^6.1.11
  audioplayers: ^6.4.0
  lottie: ^3.3.1

dev_dependencies: 
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icon/
    - assets/images/tutorial/
    - assets/images/pieces/
    - assets/images/backgrounds/bg.jpg
    - assets/sounds/
    - assets/sounds/es/
    - assets/sounds/en/
    - assets/sounds/ki/
    - assets/animations/
    - assets/images/tale/SC1/
    - assets/images/tale/SC2/
    - assets/images/tale/SC3/
    - assets/images/tale/SC4/
    - assets/images/tale/SC5/
    - assets/images/tale/SC6/
    - assets/images/tale/SC7/
    - assets/images/tale/SC8/
    - assets/images/tale/SC9/
    - assets/images/tale/SC10/
  uses-material-design: true

