name: minichess
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.10.0
  http: ^0.13.5
  connectivity_plus: ^3.0.2
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  firebase_crashlytics: ^3.0.9
  google_sign_in: ^5.4.2
  google_sign_in_web: ^0.10.2
  cloud_firestore: ^4.3.1
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

