// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPLBIy66w4VZi00U81tOWTE6UM9ESJVow',
    appId: '1:733138640689:web:47d24419fd734df97cda10',
    messagingSenderId: '733138640689',
    projectId: 'minichess-34a02',
    authDomain: 'minichess-34a02.firebaseapp.com',
    storageBucket: 'minichess-34a02.appspot.com',
    measurementId: 'G-P2N0RVSCTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA21rOFltUgylZQ2iEVv7pGTg_FmROrWu0',
    appId: '1:733138640689:android:7703ef4d030ee3cd7cda10',
    messagingSenderId: '733138640689',
    projectId: 'minichess-34a02',
    storageBucket: 'minichess-34a02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCksxJykXANRAyEfnwzmFOzxCN8K9KasBE',
    appId: '1:733138640689:ios:b9487d6bf98099367cda10',
    messagingSenderId: '733138640689',
    projectId: 'minichess-34a02',
    storageBucket: 'minichess-34a02.appspot.com',
    iosClientId: '733138640689-vjqtt0thgisop6s7t2lrr97vcfisb2li.apps.googleusercontent.com',
    iosBundleId: 'com.example.minichess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCksxJykXANRAyEfnwzmFOzxCN8K9KasBE',
    appId: '1:733138640689:ios:b9487d6bf98099367cda10',
    messagingSenderId: '733138640689',
    projectId: 'minichess-34a02',
    storageBucket: 'minichess-34a02.appspot.com',
    iosClientId: '733138640689-vjqtt0thgisop6s7t2lrr97vcfisb2li.apps.googleusercontent.com',
    iosBundleId: 'com.example.minichess',
  );
}
