/// Every intro-tale image, listed so they can be precached before the story
/// plays (see `HomeController.prepareHome`). Keep in sync with the layers built
/// in `IntroTaleController`.
const List<String> taleImagePaths = [
  'assets/images/tale/SC1/bg4.png',
  'assets/images/tale/SC1/bg3.png',
  'assets/images/tale/SC1/bg2.png',
  'assets/images/tale/SC1/bg1.png',
  'assets/images/tale/SC1/ch.png',
  'assets/images/tale/SC2/bg4.png',
  'assets/images/tale/SC2/bg3.png',
  'assets/images/tale/SC2/bg2.png',
  'assets/images/tale/SC2/bg1.png',
  'assets/images/tale/SC3/bg4.png',
  'assets/images/tale/SC3/bg3.png',
  'assets/images/tale/SC3/bg2.png',
  'assets/images/tale/SC3/bg1.png',
  'assets/images/tale/SC4/bg4.png',
  'assets/images/tale/SC4/bg3.png',
  'assets/images/tale/SC4/bg2.png',
  'assets/images/tale/SC4/bg1.png',
  'assets/images/tale/SC4/ch.png',
  'assets/images/tale/SC5/bg4.png',
  'assets/images/tale/SC5/bg3.png',
  'assets/images/tale/SC5/bg2.png',
  'assets/images/tale/SC5/bg1.png',
  'assets/images/tale/SC5/ch.png',
  'assets/images/tale/SC6/bg4.png',
  'assets/images/tale/SC6/bg3.png',
  'assets/images/tale/SC6/bg2.png',
  'assets/images/tale/SC6/bg1.png',
  'assets/images/tale/SC6/ch.png',
  'assets/images/tale/SC7/bg4.png',
  'assets/images/tale/SC7/bg3.png',
  'assets/images/tale/SC7/bg2.png',
  'assets/images/tale/SC7/bg1.png',
  'assets/images/tale/SC8/bg4.png',
  'assets/images/tale/SC8/bg3.png',
  'assets/images/tale/SC8/bg2.png',
  'assets/images/tale/SC8/bg1.png',
  'assets/images/tale/SC9/bg4.png',
  'assets/images/tale/SC9/bg3.png',
  'assets/images/tale/SC9/bg2.png',
  'assets/images/tale/SC9/bg1.png',
  'assets/images/tale/SC10/ch.png',
];
